# reference files
ref_fa: "hg38.fa"
# BED file with a set of region to restrict the evaluation. Multiple allowed but must match names in 'regions' below. 
nonrep: "bed/hg38_non_repeats.bed"
## simple repeat annotation (recommended but optional. Comment next line to disable)
simprep_bed: "bed/simpleRepeat_GRCh38.bed.gz"
# vcfs to analyze
exp: 'hgsvc'
samples: 'HG00514 NA19240'
methods: 'vg bayestyper'
# output PDF with all the graphs
out_prefix: 'hgsvc-vg-bayestyper'
# which type of evaluation?
#   - 'call' is SV presence/absence
#   - 'geno' compares actual genotypes
eval: 'call geno'
# which SVs to consider?
#   - 'all' means all genome (i.e. no filtering)
#   - 'nonrep' means only SVs overlapping non-repeat regions (as defined by *nonrep_bed* above).
regions: 'all nonrep'
# should we look for inversions by comparing the sequence of the REF and ALT alleles?
check_inv: False
# minimum coverage/reciprocal overlap to match variants from the call-set and truth-set
min_cov: 0.5
# ENV modules
envm:
  bgzip: ["bioinfo/samtools/1.14"]
  bcftools: ["bioinfo/samtools/1.14", "bioinfo/Bcftools/1.17"]
  sveval: ["statistics/R/4.3.0"]
  
  
