# reference files
ref_fa: "hs37d5.fa"
conf: "bed/conf.bed"
# vcfs to analyze
exp: 'giab'
samples: 'HG002'
methods: 'vg'
# output PDF with all the graphs
out_pdf: 'giab-vg-HG002.pdf'
# which type of evaluation?
#   - 'call' is SV presence/absence
#   - 'geno' compares actual genotypes
eval: 'call geno'
# which SVs to consider?
#   - 'all' means all genome (i.e. no filtering)
#   - 'nonrep' means only SVs overlapping non-repeat regions (as defined by *nonrep_bed* above).
regions: 'all conf'
# should we look for inversions by comparing the sequence of the REF and ALT alleles?
check_inv: False
# minimum coverage/reciprocal overlap to match variants from the call-set and truth-set
min_cov: 0.5
# ENV modules
envm:
  bgzip: "bioinfo/samtools/1.14"
  bcftools: "bioinfo/Bcftools/1.17"
  sveval: "statistics/R/4.3.0"
